import { createContext,useContext,useEffect,useMemo,useState,type ReactNode } from "react";
export type Lang="pt"|"en"|"es"; type Dict=Record<string,string>;

const pt:Dict={
"nav.home":"Início","nav.about":"O Instituto","nav.specialties":"Procedimentos","nav.tech":"Método Pilare®","nav.team":"Equipe","nav.structure":"Filosofia","nav.contact":"Contato",
"cta.book":"Agendar avaliação","cta.trajectory":"Conhecer o Instituto","cta.whatsapp":"Falar com o Instituto","cta.visit":"Agendar avaliação","cta.book.person":"Agendar",
"hero.eyebrow":"Instituto Montalvão · Harmonização Orofacial","hero.title.a":"Rosto não é","hero.title.gold":"tendência.","hero.title.b":"É identidade.","hero.text":"Harmonização Orofacial com planejamento, precisão e naturalidade para valorizar aquilo que torna cada rosto único.","hero.scroll":"Conheça o Instituto",
"about.eyebrow":"Dr. Samuel Montalvão","about.title":"A beleza de cada rosto começa pela sua identidade.","about.text":"O Dr. Samuel Montalvão é Cirurgião-Dentista, especialista em Harmonização Orofacial, com atuação voltada à estética facial, equilíbrio das proporções e gerenciamento do envelhecimento. Sua abordagem é individualizada: preservar a identidade, respeitar a anatomia e utilizar técnicas de forma estratégica para resultados harmônicos e naturais.","about.c1":"Planejamento individualizado","about.c2":"Naturalidade e preservação da identidade","about.c3":"Estética integrada à saúde",
"barbies.eyebrow":"Método Pilare®","barbies.title":"Uma abordagem estratégica para valorizar a identidade de cada rosto.","barbies.text":"O Método Pilare® representa o posicionamento do Dr. Samuel Montalvão em torno de planejamento, proporção, naturalidade e individualidade.","barbies.p1":"Individualidade","barbies.p2":"Planejamento","barbies.p3":"Equilíbrio e naturalidade",
"spec.eyebrow":"Harmonização Orofacial","spec.title":"Procedimentos pensados para cada rosto.","spec.text":"Conheça as principais possibilidades e converse com o Instituto sobre a indicação adequada ao seu caso.","spec.breast":"Harmonização Orofacial","spec.breast.d":"Planejamento individualizado para equilíbrio, proporção e naturalidade facial.","spec.body":"Preenchimento Facial","spec.body.d":"Ácido hialurônico para estruturação, contorno, definição e refinamento de proporções.","spec.face":"Toxina Botulínica","spec.face.d":"Aplicações conforme indicação e planejamento individual.","spec.intimate":"Bioestimuladores","spec.intimate.d":"Estratégias de biomodulação voltadas à qualidade, firmeza e viço da pele.",
"tech.eyebrow":"Filosofia de tratamento","tech.title":"Estética não se sustenta sem saúde.","tech.mila":"Individualidade","tech.mila.d":"Cada rosto possui características próprias.","tech.bra":"Naturalidade","tech.bra.d":"Preservar a identidade e evitar resultados artificiais.","tech.hd":"Planejamento","tech.hd.d":"Cada procedimento faz parte de uma estratégia individualizada.",
"authority.eyebrow":"Princípios","authority.title":"O que orienta cada decisão.","authority.s1":"Individualidade","authority.s2":"Naturalidade","authority.s3":"Planejamento","authority.s4":"Saúde",
"exp.eyebrow":"Primeira consulta","exp.title":"Tudo começa com uma avaliação individualizada.","exp.i1":"Compreender queixas e expectativas","exp.i2":"Analisar o rosto e o histórico","exp.i3":"Definir possibilidades e prioridades","exp.i4":"Construir um planejamento personalizado",
"test.eyebrow":"Experiência","test.title":"Cuidado individual, do primeiro contato ao planejamento.","test.q1":"Cada rosto possui características próprias e merece uma estratégia personalizada.","test.q2":"O objetivo é valorizar a identidade, não criar um padrão.","test.q3":"Estética e saúde devem caminhar juntas.",
"goal.eyebrow":"Atendimento","goal.title":"O que você deseja compreender?","goal.g1":"Conhecer as possibilidades para meu rosto","goal.g2":"Avaliar preenchimentos ou contorno facial","goal.g3":"Conhecer toxina ou bioestimuladores","goal.g4":"Agendar uma avaliação individualizada",
"faq.eyebrow":"Perguntas frequentes","faq.title":"Antes de agendar.","faq.q1":"Como funciona a primeira consulta?","faq.a1":"É o momento de acolher suas queixas, avaliar o histórico, analisar o rosto, compreender expectativas e construir um planejamento individualizado.","faq.q2":"Preciso saber qual procedimento quero fazer?","faq.a2":"Não. A consulta existe justamente para compreender suas características, necessidades e expectativas e então definir as possibilidades.","faq.q3":"Quanto custa a consulta?","faq.a3":"A consulta de avaliação custa R$ 580,00. O pagamento pode ser feito por Pix ou link de pagamento, conforme informado pelo Instituto.","faq.q4":"Posso fazer a consulta online?","faq.a4":"Sim. O Instituto informa disponibilidade para avaliação presencial ou online.",
"intl.eyebrow":"Filosofia","intl.title":"Estética não se sustenta sem saúde.","intl.text":"O trabalho é orientado por individualidade, naturalidade, planejamento, equilíbrio e respeito à saúde facial.","intl.b1":"Individualidade em cada planejamento","intl.b2":"Naturalidade como princípio","intl.b3":"Respeito às proporções e à anatomia","intl.b4":"Estética integrada à saúde",
"diff.eyebrow":"Diferenciais","diff.title":"Uma abordagem centrada na identidade.","diff.item1.t":"Individualidade","diff.item1.d":"Cada rosto possui características próprias.","diff.item2.t":"Naturalidade","diff.item2.d":"Resultados planejados para preservar a identidade.","diff.item3.t":"Planejamento","diff.item3.d":"Estratégia individual antes de qualquer procedimento.","diff.item4.t":"Equilíbrio","diff.item4.d":"Proporções e anatomia orientam o planejamento.","diff.item5.t":"Saúde","diff.item5.d":"A estética não é dissociada da saúde.","diff.item6.t":"Precisão","diff.item6.d":"Técnicas escolhidas conforme indicação profissional.","diff.item7.t":"Acolhimento","diff.item7.d":"Escuta das expectativas e prioridades.","diff.item8.t":"Cuidado individual","diff.item8.d":"Um plano construído para cada paciente.",
"stats.eyebrow":"Instituto Montalvão","stats.title":"Identidade, naturalidade e planejamento.","stats.item1.label":"Individualidade","stats.item2.label":"Naturalidade","stats.item3.label":"Planejamento","stats.item4.label":"Saúde",
"final.title":"Sua avaliação começa com uma conversa.","final.text":"Fale com o Instituto Montalvão e agende uma avaliação com o Dr. Samuel.",
"wa.default":"Olá! Gostaria de agendar uma avaliação com o Dr. Samuel Montalvão.","wa.goal":"Olá! Gostaria de saber mais sobre:","wa.visit":"Olá! Gostaria de agendar uma avaliação com o Dr. Samuel Montalvão.","wa.quiz":"Olá! Gostaria de agendar uma avaliação com o Dr. Samuel Montalvão.","wa.team.book":"Olá! Gostaria de agendar com {name}.",
"footer.rights":"Todos os direitos reservados.","footer.disclaimer":"Conteúdo informativo. Procedimentos e indicações dependem de avaliação profissional individualizada.",
"contact.title":"Vamos conversar.","contact.desc":"Nossa equipe responde pelo WhatsApp para orientar sobre avaliação presencial ou online.","contact.address":"Contato","contact.whatsapp":"WhatsApp","contact.email":"E-mail","contact.hours":"Atendimento",
"contact.visit.title":"Primeira consulta","contact.visit.subtitle":"Como funciona sua avaliação","contact.visit.step1":"A consulta acolhe suas principais queixas e expectativas.","contact.visit.step2":"O rosto, histórico e possibilidades são avaliados individualmente.","contact.visit.step3":"O planejamento considera prioridades e indicação profissional.","contact.visit.step4":"Consulta de avaliação: R$ 580,00, por Pix ou link de pagamento.","contact.visit.step5":"O valor da consulta é abatido do procedimento realizado, conforme orientação do Instituto.",
"form.eyebrow":"Agendamento","form.title":"Reserve sua avaliação.","form.desc":"Preencha os dados e continue o atendimento pelo WhatsApp.","form.name":"Nome completo","form.phone":"Telefone","form.whatsapp":"WhatsApp","form.email":"E-mail","form.city":"Cidade","form.goal":"Objetivo","form.message":"Mensagem","form.select":"Selecione","form.submit":"Agendar avaliação","form.sending":"Enviando","form.sent":"Enviado — continue no WhatsApp","form.disclaimer":"Seus dados são usados apenas para o contato do agendamento.",
"team.eyebrow":"Equipe","team.title":"Instituto Montalvão","team.intro":"Profissionais apresentados no material do Instituto, preservando a identidade de cada atuação sem inventar títulos ou especialidades.","team.manifesto.title":"Cuidado individual começa com escuta e planejamento.","team.manifesto.p1":"O Instituto Montalvão trabalha com uma visão centrada na individualidade de cada paciente.","team.manifesto.p2":"O objetivo é unir precisão, naturalidade, equilíbrio e responsabilidade.","team.manifesto.p3":"Rosto não é tendência. É identidade.",
"team.member.samuel.role":"Cirurgião-Dentista | Harmonização Orofacial","team.member.samuel.desc":"Especialista em Harmonização Orofacial. Criador do Método Pilare®.","team.member.cassio.role":"Equipe Instituto Montalvão","team.member.cassio.desc":"Profissional apresentado no material do Instituto.","team.member.isadora.role":"Equipe Instituto Montalvão","team.member.isadora.desc":"Profissional apresentada no material do Instituto.","team.member.nathaly.role":"Equipe Instituto Montalvão","team.member.nathaly.desc":"Profissional apresentada no material do Instituto.","team.member.victor.role":"Equipe Instituto Montalvão","team.member.victor.desc":"Profissional apresentado no material do Instituto.",
"spec_page.eyebrow":"Procedimentos","spec_page.title":"Harmonização Orofacial.","spec_page.intro":"Procedimentos e possibilidades do Instituto Montalvão, sempre condicionados à avaliação profissional.","spec_page.wa":"Olá! Gostaria de saber mais sobre:","spec_page.g1.name":"Harmonização Orofacial","spec_page.g1.i1.t":"Preenchimento Facial","spec_page.g1.i1.d":"Estruturação, contorno, definição e refinamento de proporções.","spec_page.g1.i2.t":"Preenchimento Labial","spec_page.g1.i2.d":"Contorno, proporção, definição e equilíbrio.","spec_page.g1.i3.t":"Rinomodelação","spec_page.g1.i3.d":"Refinamento e equilíbrio das proporções nasais conforme avaliação.","spec_page.g2.name":"Toxina e Bioestimulação","spec_page.g2.i1.t":"Toxina Botulínica","spec_page.g2.i1.d":"Aplicações conforme indicação e planejamento individual.","spec_page.g2.i2.t":"Bioestimuladores de Colágeno","spec_page.g2.i2.d":"Radiesse, Sculptra e estratégias de biomodulação conforme indicação.","spec_page.g2.i3.t":"Fios de PDO","spec_page.g2.i3.d":"Fios de sustentação e fios lisos para estímulo de colágeno e suporte.","spec_page.g3.name":"Procedimentos Complementares","spec_page.g3.i1.t":"Bichectomia","spec_page.g3.i1.d":"Procedimento cirúrgico voltado à remoção da bola de Bichat.","spec_page.g3.i2.t":"Regeneração e Biomodulação","spec_page.g3.i2.d":"PRP, I-PRF, mesclas de biomodulação, exossomos e ExoCube quando indicados.","spec_page.g3.i3.t":"Terapias Capilares","spec_page.g3.i3.d":"Estratégias voltadas à regeneração folicular, queda, volume e qualidade dos fios.",
"tech_page.eyebrow":"Método Pilare®","tech_page.title":"Uma abordagem estratégica para valorizar a identidade de cada rosto.","tech_page.intro":"O Método Pilare® é apresentado no material como criação do Dr. Samuel Montalvão. Não são adicionadas informações técnicas além das disponíveis.","tech_page.item.pilare.title":"Método Pilare®","tech_page.item.pilare.desc":"Abordagem estratégica para valorizar a identidade de cada rosto.","tech_page.item.planning.title":"Planejamento","tech_page.item.planning.desc":"Cada procedimento deve fazer parte de uma estratégia individualizada.","tech_page.item.natural.title":"Naturalidade","tech_page.item.natural.desc":"Preservar a identidade e evitar resultados artificiais.","tech_page.item.health.title":"Saúde","tech_page.item.health.desc":"Estética não se sustenta sem saúde.","tech_page.item.biomodulation.title":"Biomodulação","tech_page.item.biomodulation.desc":"Estratégias selecionadas conforme avaliação e indicação profissional.","tech_page.item.precision.title":"Precisão","tech_page.item.precision.desc":"Técnicas e proporções consideradas de maneira individual.",
"clinic.comfort":"Um espaço pensado para uma experiência individualizada.","marquee.item1":"Identidade","marquee.item2":"Naturalidade","marquee.item3":"Planejamento","marquee.item4":"Precisão","marquee.item5":"Saúde","marquee.item6":"Harmonização Orofacial","marquee.item7":"Instituto Montalvão","marquee.item8":"Método Pilare®",
"success.eyebrow":"Resultados","success.title":"Cada caso é único.","success.disclaimer":"Resultados e indicações variam conforme características individuais e avaliação profissional.","success.case1.t":"Harmonização Orofacial","success.case1.q":"Planejamento individualizado e respeito à identidade.","success.case1.a":"Instituto Montalvão","success.case2.t":"Preenchimento Facial","success.case2.q":"Estratégia de proporções e contorno conforme avaliação.","success.case2.a":"Instituto Montalvão","success.case3.t":"Toxina Botulínica","success.case3.q":"Aplicação planejada conforme indicação profissional.","success.case3.a":"Instituto Montalvão","success.case4.t":"Bioestimulação","success.case4.q":"Estratégias voltadas à qualidade da pele conforme indicação.","success.case4.a":"Instituto Montalvão","success.cta":"Agendar avaliação",
"consultant.eyebrow":"Avaliação","consultant.title.a":"Conheça as possibilidades para","consultant.title.gold":"o seu rosto","consultant.description":"Esta experiência é informativa e não substitui avaliação profissional.","consultant.step1":"Passo 1 · Qual é o seu objetivo?","consultant.reportTitle":"Orientação inicial","consultant.ctaTitle":"Pronto para sua avaliação?","consultant.ctaDesc":"Converse com o Instituto Montalvão.","consultant.ctaBtn":"Agendar pelo WhatsApp","consultant.reportEyebrow":"Informativo","consultant.reportDisclaimer":"A indicação final depende de avaliação profissional.","consultant.specialistEyebrow":"Especialista","consultant.specialistBtn":"Conhecer","consultant.statsText":"Avaliação individualizada.","consultant.statsSub":"Naturalidade e planejamento.","consultant.analysis":"Possibilidades","consultant.simulation":"Orientação",
"facial.eyebrow":"Harmonização Orofacial","facial.title.a":"Valorize","facial.title.gold":"a sua identidade","facial.description":"Conheça possibilidades de tratamento facial de forma informativa. A indicação final depende de avaliação profissional.","facial.step1":"Passo 1 · O que deseja compreender?","facial.reportTitle":"Orientação facial","facial.ctaTitle":"Pronto para sua avaliação?","facial.ctaDesc":"Agende uma avaliação com o Dr. Samuel Montalvão.","facial.ctaBtn":"Agendar por WhatsApp","facial.reportEyebrow":"Informativo","facial.reportDisclaimer":"Esta orientação não substitui avaliação profissional.","facial.specialistEyebrow":"Especialista","facial.specialistBtn":"Conhecer o Dr. Samuel","facial.statsText":"Planejamento individualizado.","facial.statsSub":"Preservação da identidade.","facial.analysis":"Pontos de atenção","facial.simulation":"Orientação",
"consultant.legal":"Esta experiência é exclusivamente ilustrativa e não substitui avaliação profissional.",
"tips.photo":"Imagem frontal, bem iluminada.","tips.light":"Use boa iluminação.","tips.front":"Fotografia de frente.","tips.filter":"Evite filtros.","tips.teeth":"Siga as orientações exibidas.",
"consultant.error.size":"Envie uma imagem de até 8 MB.","consultant.error.gen":"Não foi possível gerar a orientação.","wa.smile.message":"Olá! Gostaria de agendar uma avaliação com o Dr. Samuel Montalvão.","wa.facial.message":"Olá! Gostaria de agendar uma avaliação com o Dr. Samuel Montalvão."
};

["marquee.item9","marquee.item10","marquee.item11","marquee.item12","marquee.item13","marquee.item14"].forEach((k,i)=>{pt[k]=["Cuidado","Ciência","Equilíbrio","Precisão","Saúde","Experiência"][i]});
const en:Dict={...pt}; const es:Dict={...pt}; const dicts={pt,en,es};
type I18nValue={lang:Lang;setLang:(l:Lang)=>void;t:(key:string)=>string};
const C=createContext<I18nValue|null>(null);
export function I18nProvider({children}:{children:ReactNode}){const [lang,setLang]=useState<Lang>("pt");useEffect(()=>{const s=localStorage.getItem("montalvao-lang") as Lang|null;if(s&&s in dicts)setLang(s)},[]);useEffect(()=>localStorage.setItem("montalvao-lang",lang),[lang]);const value=useMemo(()=>({lang,setLang,t:(key:string)=>dicts[lang][key]??dicts.pt[key]??key}),[lang]);return <C.Provider value={value}>{children}</C.Provider>}
export function useI18n(){const c=useContext(C);if(!c)throw new Error("useI18n must be used within I18nProvider");return c}
